@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Agent" as ADM
participant ":MakeAdvertisementUI" as UI
participant ":MakeAdvertisementController" as CTRL
participant "manageEmployeeRepository\n:ManageEmployeeRepository" as manageEmployees
participant "manageAdvertisementRepository\n:ManageAdvertisementRepository" as manageAdvertisement
participant "Advertisement:\nAdvertisement" as Advertisement
participant "manageRequestRepository\n:ManageRequestRepository" as manageRequests
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "advertisementRepository:\nAdvertisementRepository" as AdvertisementRepository
participant "filterRepository:\nFilterRepository" as FilterRepository

activate ADM

        ADM -> UI : asks to create property advertisement

        activate UI

            UI -> CTRL** : create

            UI -> CTRL : getAgents()
            activate CTRL

                CTRL -> manageAdvertisement : getAgent()
                        activate manageAdvertisement

                            manageAdvertisement -> RepositorySingleton : getInstance()
                            activate RepositorySingleton

                            RepositorySingleton --> manageAdvertisement: repositories
                            deactivate RepositorySingleton

                            manageAdvertisement -> PLAT : getEmployeeRepository
                            activate PLAT

                            PLAT --> manageAdvertisement: EmployeeRepository
                            deactivate PLAT

                            manageAdvertisement -> EmployeeRepository : getEmployeeByEmail()
                            activate EmployeeRepository

                            EmployeeRepository -> UserSession : getUserID()
                            activate UserSession

                            UserSession -> EmployeeRepository : UserID
                            deactivate UserSession

                            EmployeeRepository --> manageAdvertisement : EmployeeInfo
                            deactivate EmployeeRepository

                            manageAdvertisement --> CTRL : Agent
                            deactivate manageAdvertisement

            CTRL --> UI : Agent
        deactivate CTRL

            UI -> CTRL : getTypeOfProperties()
                        activate CTRL

                            CTRL -> RepositorySingleton : getInstance()
                                activate RepositorySingleton

                                    RepositorySingleton --> CTRL: repositories
                                deactivate RepositorySingleton

                                CTRL -> PLAT : getFilterRepository()
                                activate PLAT

                                PLAT --> CTRL: FilterRepository
                                deactivate PLAT

                                CTRL -> FilterRepository : getTypeOfProperties()
                                activate FilterRepository

                                FilterRepository --> CTRL : TypeOfPropertiesList
                                deactivate FilterRepository

                            CTRL --> UI : TypeOfPropertiesList
                        deactivate CTRL

                        UI -> CTRL : getTypeOfCommission()
                                                activate CTRL

                                                    CTRL -> RepositorySingleton : getInstance()
                                                        activate RepositorySingleton

                                                            RepositorySingleton --> CTRL: repositories
                                                        deactivate RepositorySingleton

                                                        CTRL -> PLAT : getFilterRepository()
                                                        activate PLAT

                                                        PLAT --> CTRL: FilterRepository
                                                        deactivate PLAT

                                                        CTRL -> FilterRepository : getTypeOfCommission()
                                                        activate FilterRepository

                                                        FilterRepository --> CTRL : TypeOfCommissionList
                                                        deactivate FilterRepository

                                                    CTRL --> UI : TypeOfCommissionList
                                                deactivate CTRL

                        UI -> CTRL : getTypeOfBusiness()
                                                activate CTRL
                                                
                                                    CTRL -> RepositorySingleton : getInstance()
                                                        activate RepositorySingleton

                                                            RepositorySingleton --> CTRL: repositories
                                                        deactivate RepositorySingleton

                                                        CTRL -> PLAT : getFilterRepository()
                                                        activate PLAT

                                                        PLAT --> CTRL: FilterRepository
                                                        deactivate PLAT

                                                        CTRL -> FilterRepository : getTypeOfBusiness()
                                                        activate FilterRepository

                                                        FilterRepository --> CTRL : TypeOfBusinessList
                                                        deactivate FilterRepository

                                                    CTRL --> UI : TypeOfBusinessList
                                                deactivate CTRL

            UI --> ADM : shows list of agents and Advertisement's selected data (Type of Property,\n type of business, type of commission)  and asks to select the data
        deactivate UI

    ADM -> UI : selects data
    activate UI

        UI --> ADM : request data
    deactivate UI

    ADM -> UI : types requested data (price, area, distance to city center, address,\n photographs(linkURI), commission value)
    activate UI

    alt typeOfBusiness = Rent

    alt typeOfProperty = House || Apartment

        UI --> ADM : request data
    deactivate UI

    ADM -> UI : types requested data (nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation)
        activate UI

            alt typeOfProperty = House

            UI --> ADM : request data
        deactivate UI

        ADM -> UI : types requested data (SunExposure, Basement, Loft)
            activate UI

            end
            end

UI --> ADM : shows selected and typed data
            deactivate UI
    ADM -> UI : submits data
    activate UI

        UI -> CTRL : submitAdvertisement(price, area, distCityCenter, address,\n photographs(linkURI), commission value,\ nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation, SunExposure, Basement, Loft,\n TypeofBusiness, TypeofProperty, TypeofCommission, agent)
        activate CTRL

                    CTRL -> manageAdvertisement : submitAdvertisement(price, area, distCityCenter, address,\n photographs(linkURI), commission value,\ nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation, SunExposure, Basement, Loft,\n TypeofBusiness, TypeofProperty, TypeofCommission, agent)
                    activate manageAdvertisement

                    manageAdvertisement -> manageRequests : createRequest(price, area, distCityCenter, address,\n photographs(linkURI),\ nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation, SunExposure, Basement, Loft,\n TypeofBusiness, TypeofProperty, Agent)
                    activate manageRequests

                                        manageRequests ->manageRequests : getDate()
                                                            activate manageRequests

                                                            manageRequests --> manageRequests : dateOfRequest
                                                            deactivate manageRequests

                                                            manageRequests -> Property** : createProperty(price, area, distCityCenter, address,\n photographs(linkURI),\ nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation, SunExposure, Basement, Loft,\n TypeofBusiness, TypeofProperty)


                                                            manageRequests -> Request** : createRequest(property, agent, dateOfRequest)

manageRequests --> manageAdvertisement : request
deactivate manageRequests

                    manageAdvertisement ->manageAdvertisement : getDate()
                    activate manageAdvertisement

                    manageAdvertisement --> manageAdvertisement : dateOfAdvertisement
                    deactivate manageAdvertisement

                                       manageAdvertisement -> Advertisement** : createAdvertisement(request, typeOfCommission, commissionValue, dateOfAdvertisement)

                                        manageAdvertisement -> manageAdvertisement : validateAdvertisement(Advertisement)

                         manageAdvertisement -> RepositorySingleton : getInstance()
                                activate RepositorySingleton

                                    RepositorySingleton --> manageAdvertisement: repositories
                                deactivate RepositorySingleton

                                manageAdvertisement -> PLAT : getAdvertisementRepository()
                                activate PLAT

                                    PLAT --> manageAdvertisement: AdvertisementRepository
                                deactivate PLAT

                                manageAdvertisement -> AdvertisementRepository : addAdvertisement(Advertisement)
                                activate AdvertisementRepository

                                AdvertisementRepository --> manageAdvertisement :
                                deactivate AdvertisementRepository

                                manageAdvertisement --> CTRL : Advertisement
                            deactivate manageAdvertisement

          CTRL -> UI: Advertisement
          deactivate CTRL
    UI -> ADM: show operation success
    deactivate UI

deactivate ADM
@enduml