@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide empty fields

'endereco .... cidade, distrito, cidade....

class client{
}
@enduml