@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 001

autonumber

actor "Unregistered User" as User
participant ":System" as System

activate User

    User -> System : Asks to list properties
    activate System

    System --> User : Displays properties by most\n recent order and asks wants to filter

    opt Filters
    deactivate System

    User -> System : Asks to filter properties
    activate System

            System --> User : Displays sorting criteria list
        deactivate System
    opt sorting criteria
            User -> System : Selects sorting criteria
        activate System
    end
        System --> User : Displays type of property filter
    deactivate System

    opt type of property
            User -> System : Selects property filter
        activate System
    end
        System --> User : Displays type of business filter
    deactivate System

    opt type of business
            User -> System : Selects business filter
        activate System
    end

        System --> User : Displays number of rooms list
    deactivate System

    opt number of rooms
            User -> System : Selects number of rooms
        activate System
    end

        System --> User : Displays selected data
    deactivate System

        User -> System : Submits data
    activate System

        System --> User : Displays all properties that suit the filters
    deactivate System

    |||
    end

deactivate User

@enduml