@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as User
participant ":ListPropertyUI" as UI
participant ":ListPropertyController" as CTRL
participant "manageAdvertisementRepository\n:manageAdvertisementRepository" as manageAdvertisement
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "advertisementRepository\n:AdvertisementRepository" as advertisementRepository
participant "sortingMethodsRepository\n:SortingMethodsRepository" as sortingCriteriaRepository
participant "numberOfBedroomsRepository\n:NumberOfBedroomsRepository" as numberOfBedroomsRepository
participant "typeOfBusinessRepository\n:TypeOfBusinessRepository" as typeOfBusinessRepository
participant "typeOfPropertyRepository\n:TypeOfPropertyRepository" as typeOfPropertyRepository
participant "propertyRepository\n:PropertyRepository" as propertyRepository
participant "comparatorAscendingPrice\n:comparatorAscendingPrice" as ComparatorAscendingPrice
participant "comparatorDescendingPrice\n:ComparatorDescendingPrice" as ComparatorDescendingPrice
participant "cityAlphabetic\n:CityAlphabetic" as CityAlphabetic
participant "cityAlphabeticReverse\n:CityAlphabeticReverse" as CityAlphabeticReverse
participant "stateAlphabetic\n:StateAlphabetic" as StateAlphabetic
participant "stateAlphabeticReverse\n:StateAlphabeticReverse" as StateAlphabeticReverse


activate User

        User -> UI : Asks to list properties

        activate UI

            UI -> CTRL** : create

            UI -> CTRL : displaysList()
            activate CTRL

                CTRL -> manageAdvertisement : getAdvertisements()
                activate manageAdvertisement

                    manageAdvertisement -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                    RepositorySingleton --> manageAdvertisement: repositories
                    deactivate RepositorySingleton

                    manageAdvertisement -> PLAT : getSortingMethodsRepository
                    activate PLAT

                    PLAT --> manageAdvertisement: PropertyRepository
                    deactivate PLAT

                    manageAdvertisement -> advertisementRepository : getAdvertisements()
                    activate advertisementRepository

                    advertisementRepository --> manageAdvertisement : advertisementsList
                    deactivate advertisementRepository

                    manageAdvertisement --> CTRL : advertisementsList
                    deactivate manageAdvertisement

                CTRL -> UI : displaysList(advertisementsList)
                deactivate CTRL

            UI --> User : Displays properties by most recent order
            deactivate UI

    opt Filters

            User -> UI : Asks to filter properties
            activate UI

            UI -> CTRL : displaysList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getPropertiesRepository()
                activate PLAT

                PLAT --> CTRL: sortingCriteriaRepository
                deactivate PLAT

                CTRL -> sortingCriteriaRepository : getSortingMethods()
                activate sortingCriteriaRepository

                sortingCriteriaRepository --> CTRL : SortingMethods
                deactivate sortingCriteriaRepository

                CTRL --> UI : displaysList(sortingCriteria)
                deactivate CTRL


        UI --> User : Displays sorting criterias list
    deactivate UI

        User -> UI : Selects sorting criteria
    activate UI

            UI -> CTRL : displaysList()
            activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getTypeOfPropertyRepository()
            activate PLAT

            PLAT --> CTRL: typeOfPropertyRepository
            deactivate PLAT

            CTRL -> typeOfPropertyRepository : getListTypeOfProperty()
            activate typeOfPropertyRepository

            typeOfPropertyRepository --> CTRL : ListTypeOfProperty
            deactivate typeOfPropertyRepository

            CTRL --> UI : displaysList(ListTypeOfProperty)
            deactivate CTRL

        UI --> User : Displays type of property filter
        deactivate UI

    alt Type Of Property = Land || Apartment || House

        User -> UI : Selects type of property filter
        activate UI

    end
        UI -> CTRL : displaysList()

        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : typeOfBusinessRepository()
            activate PLAT

            PLAT --> CTRL: typeOfBusinessRepository
            deactivate PLAT

            CTRL -> typeOfBusinessRepository : getListTypeOfBusiness()
            activate typeOfBusinessRepository

            typeOfBusinessRepository --> CTRL : ListTypeOfBusiness
            deactivate typeOfBusinessRepository

            CTRL --> UI : displaysList(ListTypeOfBusiness)
            deactivate CTRL

        UI --> User : Displays type of business filter

        deactivate UI

    alt Type Of Business = Sale || Rent

        User -> UI : Selects type of business filter
        activate UI

    end
        UI -> CTRL : displaysList()

        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getNumberOfBedroomsRepository()
            activate PLAT

            PLAT --> CTRL: numberOfBedroomsRepository
            deactivate PLAT

            CTRL -> numberOfBedroomsRepository : getListNumberOfBedrooms()
            activate numberOfBedroomsRepository

            numberOfBedroomsRepository --> CTRL : ListNumberOfBedrooms
            deactivate numberOfBedroomsRepository

            CTRL --> UI : displaysList(ListNumberOfBedrooms)
            deactivate CTRL

        UI --> User : Displays number of bedrooms filter

        deactivate UI

        alt Number Of Bedrooms = T0 || T1 || T2 || T3 || T4 || T5 || T5+

        User -> UI : Selects type of business filter
            activate UI
        end

        UI --> User : Displays selected data
        deactivate UI


        User -> UI : Submits data
    activate UI



     UI -> CTRL : getSortedListByFilters(typeOfBusiness,\ntypeOfProperty,numberOfBedrooms, sortingMethod)
     activate CTRL

             CTRL -> manageAdvertisement : getSortedListByFilters(typeOfBusiness, \ntypeOfProperty, numberOfBedrooms, sortingCriteria)
         activate manageAdvertisement

                 manageAdvertisement -> RepositorySingleton : getInstance()
                 activate RepositorySingleton

                 RepositorySingleton --> manageAdvertisement: repositories
                 deactivate RepositorySingleton

                 manageAdvertisement -> PLAT : getPropertyRepository()
                 activate PLAT

                 PLAT --> manageAdvertisement : propertyRepository
                 deactivate PLAT

                manageAdvertisement --> propertyRepository : getListOfProperties
                activate propertyRepository

                propertyRepository --> manageAdvertisement : listOfProperties
                deactivate propertyRepository

                 manageAdvertisement -> manageAdvertisement : getListByFilters(typeOfBusiness, \ntypeOfProperty, numberOfBedrooms, sortingCriteria)

                      loop for each property

                         activate manageAdvertisement
                         manageAdvertisement -> manageAdvertisement : verifyPropertyByFilters(property)
                         activate manageAdvertisement
                         manageAdvertisement --> manageAdvertisement : true/false
                         deactivate manageAdvertisement

                      |||

                      end
                           manageAdvertisement --> manageAdvertisement : listOfPropertiesFiltered

                     deactivate manageAdvertisement

    manageAdvertisement -> manageAdvertisement : getSortedList(list, sortingCriteria)
    activate manageAdvertisement


         alt Sorting Method = Ascending Price


                    manageAdvertisement -> sortingCriteriaRepository : getSortingMethods(ComparatorAscendingPrice)
                    activate sortingCriteriaRepository

                    sortingCriteriaRepository --> manageAdvertisement: ComparatorAscendingPrice
                    deactivate sortingCriteriaRepository

                    manageAdvertisement -> ComparatorAscendingPrice : ComparatorAscendingPrice(advertisementsList)
                    activate ComparatorAscendingPrice

                    ComparatorAscendingPrice --> manageAdvertisement : ListSorted
                    deactivate ComparatorAscendingPrice

            |||
            else Sorting Method = Descending Price

                    manageAdvertisement -> sortingCriteriaRepository : getSortingMethods(ComparatorDescendingPrice)
                    activate sortingCriteriaRepository

                    sortingCriteriaRepository --> manageAdvertisement: ComparatorDescendingPrice
                    deactivate sortingCriteriaRepository

                    manageAdvertisement -> ComparatorDescendingPrice : ComparatorDescendingPrice(advertisementsList)
                    activate ComparatorDescendingPrice

                    ComparatorDescendingPrice --> manageAdvertisement : ListSorted
                    deactivate ComparatorDescendingPrice
            |||
            else Sorting Method = City Alphabetic

                    manageAdvertisement -> sortingCriteriaRepository : getSortingMethods(CityAlphabetic)
                    activate sortingCriteriaRepository

                    sortingCriteriaRepository --> manageAdvertisement: CityAlphabetic
                    deactivate sortingCriteriaRepository

                    manageAdvertisement -> CityAlphabetic : CityAlphabetic(advertisementsList)
                    activate CityAlphabetic

                    CityAlphabetic --> manageAdvertisement : ListSorted
                    deactivate CityAlphabetic
            |||
            else Sorting Method = City Alphabetic Reverse

                    manageAdvertisement -> sortingCriteriaRepository : getSortingMethods(CityAlphabeticReverse)
                    activate sortingCriteriaRepository

                    sortingCriteriaRepository --> manageAdvertisement: CityAlphabeticReverse
                    deactivate sortingCriteriaRepository

                    manageAdvertisement -> CityAlphabeticReverse : CityAlphabeticReverse(advertisementsList)
                    activate CityAlphabeticReverse

                    CityAlphabeticReverse --> manageAdvertisement : ListSorted
                    deactivate CityAlphabeticReverse
            |||
            else Sorting Method = State Alphabetic

                    manageAdvertisement -> sortingCriteriaRepository : getSortingMethods(StateAlphabetic)
                    activate sortingCriteriaRepository

                    sortingCriteriaRepository --> manageAdvertisement: StateAlphabetic
                    deactivate sortingCriteriaRepository

                    manageAdvertisement -> StateAlphabetic : StateAlphabetic(advertisementsList)
                    activate StateAlphabetic

                    StateAlphabetic --> manageAdvertisement : ListSorted
                    deactivate StateAlphabetic

            |||
            else Sorting Method = State Alphabetic Reverse

                    manageAdvertisement -> sortingCriteriaRepository : getSortingMethods(StateAlphabeticReverse)
                    activate sortingCriteriaRepository

                    sortingCriteriaRepository --> manageAdvertisement: StateAlphabeticReverse
                    deactivate sortingCriteriaRepository

                    manageAdvertisement -> StateAlphabeticReverse : StateAlphabeticReverse(advertisementsList)
                    activate StateAlphabeticReverse

                    StateAlphabeticReverse --> manageAdvertisement : ListSorted
                    deactivate StateAlphabeticReverse
            |||
            end

    manageAdvertisement --> manageAdvertisement : listOfPropertiesFiltered
    deactivate manageAdvertisement

    manageAdvertisement --> CTRL : listOfPropertiesFiltered
    deactivate manageAdvertisement


     CTRL --> UI: listOfPropertiesFiltered
     deactivate CTRL

    UI --> User :  Displays all properties that suit the filters
    deactivate UI


    deactivate UI

deactivate User
    end




@enduml
