@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Owner" as ADM
participant ":RequestAdvertisementUI" as UI
participant ":RequestAdvertisementController" as CTRL
participant "manageEmployeesRepository\n:ManageEmployeesRepository" as manageEmployees
participant "manageRequestRepository\n:ManageRequestRepository" as manageRequests
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "requestRepository:\nRequestRepository" as RequestRepository
participant "request:\nRequest" as Request



activate ADM

        ADM -> UI : Asks to create property ad

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getAgents()
            activate CTRL

                CTRL -> manageEmployees : getAgents()
                activate manageEmployees


                manageEmployees -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> manageEmployees: repositories
                    deactivate RepositorySingleton

                    manageEmployees -> PLAT : getEmployeeRepository()
                    activate PLAT

                        PLAT --> manageEmployees: EmployeeRepository
                    deactivate PLAT

                    manageEmployees -> manageEmployees : filterByRole(Agent)
                                        activate manageEmployees

                                        manageEmployees --> manageEmployees : listOfAgents
                                        deactivate manageEmployees

                    manageEmployees --> CTRL : listOfAgents
                deactivate manageEmployees

                CTRL --> UI : listOfAgents
            deactivate CTRL

            UI -> CTRL : getTypeOfBusiness()
                                                            activate CTRL




                                                                CTRL -> RepositorySingleton : getInstance()
                                                                    activate RepositorySingleton

                                                                        RepositorySingleton --> CTRL: repositories
                                                                    deactivate RepositorySingleton

                                                                    CTRL -> PLAT : getTypeOfBusiness()
                                                                    activate PLAT

                                                                    PLAT --> CTRL: TypeOfBusinessRepository
                                                                    deactivate PLAT

                                                                    CTRL -> typeOfBusinessRepository : getTypeOfBusiness()
                                                                    activate typeOfBusinessRepository

                                                                    typeOfBusinessRepository --> CTRL : TypeOfBusinessList
                                                                    deactivate typeOfBusinessRepository







                                                                CTRL --> UI : TypeOfBusinessList
                                                            deactivate CTRL

                                                            UI -> CTRL : getTypeOfProperties()
                                                                                    activate CTRL




                                                                                        CTRL -> RepositorySingleton : getInstance()
                                                                                            activate RepositorySingleton

                                                                                                RepositorySingleton --> CTRL: repositories
                                                                                            deactivate RepositorySingleton

                                                                                            CTRL -> PLAT : getTypeOfPropertiesRepository()
                                                                                            activate PLAT

                                                                                            PLAT --> CTRL: TypeOfPropertiesRepository
                                                                                            deactivate PLAT

                                                                                            CTRL -> typeOfPropertyRepository : getTypeOfProperties()
                                                                                            activate typeOfPropertyRepository

                                                                                            typeOfPropertyRepository --> CTRL : TypeOfPropertiesList
                                                                                            deactivate typeOfPropertyRepository







                                                                                        CTRL --> UI : TypeOfPropertiesList
                                                                                    deactivate CTRL

            UI --> ADM : shows list of agents and request's selected data (Type of Property,\n type of business)  and asks to select the data
        deactivate UI

    ADM -> UI : selects data
    activate UI

        UI --> ADM : requests data
    deactivate UI

    ADM -> UI : types requested data (price, area, distCityCenter, address,\n photographs(linkURI))
    activate UI



    alt typeOfProperty = House or Apartment

        UI --> ADM : requests data
    deactivate UI

    ADM -> UI : types requested data (nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation)
        activate UI

            alt typeOfProperty = House


            UI --> ADM : requests data
        deactivate UI

        ADM -> UI : types requested data (SunExposure, Basement, Loft, )
            activate UI



            end
            end

            UI --> ADM : shows selected and requested data
                        deactivate UI

    ADM -> UI : submits request
    activate UI

        UI -> CTRL : submitRequest(price, area, distCityCenter, address,\n photographs(linkURI),\ nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation, SunExposure, Basement, Loft, ,\n TypeofBusiness, TypeofProperty, agent)
        activate CTRL




                    CTRL -> manageRequests : submitRequest(price, area, distCityCenter, address,\n photographs(linkURI),\ nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation, SunExposure, Basement, Loft,\n TypeofBusiness, TypeofProperty, agent)
                    activate manageRequests

                    manageRequests ->manageRequests : getDate()
                    activate manageRequests

                    manageRequests --> manageRequests : dateOfRequest
                    deactivate manageRequests

                    manageRequests -> Property** : createProperty(price, area, distCityCenter, address,\n photographs(linkURI),\ nBedrooms, nBathRooms, nParkingSpaces,\n EquipmentDesignation, SunExposure, Basement, Loft,\n TypeofBusiness, TypeofProperty)


                    manageRequests -> Request** : createRequest(property, agent, dateOfRequest)

                                        manageRequests -> manageRequests : validateRequest(request)



                         manageRequests -> RepositorySingleton : getInstance()
                                activate RepositorySingleton

                                    RepositorySingleton --> manageRequests: repositories
                                deactivate RepositorySingleton

                                manageRequests -> PLAT : getRequestRepository()
                                activate PLAT

                                    PLAT --> manageRequests: RequestRepository
                                deactivate PLAT

                                manageRequests -> RequestRepository : addRequest(request)
                                activate RequestRepository

                                RequestRepository --> manageRequests :
                                deactivate RequestRepository

                                manageRequests --> CTRL : request
                            deactivate manageRequests

          CTRL -> UI: request
          deactivate CTRL
    UI -> ADM: show operation success
    deactivate UI

deactivate ADM

@enduml